"""empty message

Revision ID: 02eb038f7812
Revises: b9345991a574
Create Date: 2026-03-30 19:28:08.629128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02eb038f7812'
down_revision: Union[str, Sequence[str], None] = 'b9345991a574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_geotags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('geotag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geotag_id'], ['geotags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'geotag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_geotags')
    # ### end Alembic commands ###
