"""empty message

Revision ID: 6ea17604dedf
Revises: d1a2b3c4e5f6
Create Date: 2026-04-22 18:29:13.036166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea17604dedf'
down_revision: Union[str, Sequence[str], None] = 'd1a2b3c4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('route_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('routes', 'polyline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('polyline', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('routes', 'route_points')
    # ### end Alembic commands ###
