"""empty message

Revision ID: 844fa4931734
Revises: f4285b6ec15a
Create Date: 2026-04-18 02:47:26.894773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844fa4931734'
down_revision: Union[str, Sequence[str], None] = 'f4285b6ec15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geotags', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geotags', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
