"""empty message

Revision ID: a045312cb35e
Revises: a2a0dfad6129
Create Date: 2026-04-13 18:03:38.297267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a045312cb35e'
down_revision: Union[str, Sequence[str], None] = 'a2a0dfad6129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('start_point_id', sa.Integer(), nullable=True),
    sa.Column('finish_point_id', sa.Integer(), nullable=True),
    sa.Column('transport_type', sa.String(length=50), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('travel_time_min', sa.Integer(), nullable=True),
    sa.Column('total_visit_time_min', sa.Integer(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finish_point_id'], ['geotags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['start_point_id'], ['geotags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_author_id'), 'routes', ['author_id'], unique=False)
    op.create_index(op.f('ix_routes_finish_point_id'), 'routes', ['finish_point_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_start_point_id'), 'routes', ['start_point_id'], unique=False)
    op.create_table('route_geotags',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('geotag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geotag_id'], ['geotags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_id', 'geotag_id')
    )
    op.create_table('route_themes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_themes')
    op.drop_table('route_geotags')
    op.drop_index(op.f('ix_routes_start_point_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_finish_point_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_author_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
