"""empty message

Revision ID: f4285b6ec15a
Revises: a045312cb35e
Create Date: 2026-04-18 02:30:06.573955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4285b6ec15a'
down_revision: Union[str, Sequence[str], None] = 'a045312cb35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('geotags', sa.Column('is_moderated', sa.Boolean(), nullable=True))
    op.execute("UPDATE geotags SET is_moderated = false")
    op.alter_column('geotags', 'is_moderated', nullable=False)
    op.add_column('geotags', sa.Column('moderator_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geotags', 'moderator_comment')
    op.drop_column('geotags', 'is_moderated')
    # ### end Alembic commands ###
