[tool.poetry]
name = "hidden-trails"
version = "0.1.0"
description = "Social platform for travelers for the preservation of local and regional monuments."
authors = ["Kiryanov Vladimir vovcha5854@gmail.com"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.133.0"
uvicorn = {extras = ["standard"], version = "0.41.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
