[alembic]
sqlalchemy.url = postgresql+psycopg://postgres:postgres@localhost:5432/hidden-trails

script_location = alembic

version_table = alembic_version
version_num = 1

prepend_sys_path = .
target_metadata = app.models.Base

logfile = alembic.log