[tool.poetry]
name = "users"
version = "0.1.0"
description = "Microservices for operating with user logic."
authors = ["Kiryanov Vladimir vovcha5854@gmail.com"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.133.0"
uvicorn = {extras = ["standard"], version = "0.41.0"}
pydantic = "^2.12.5"
sqlalchemy = "^2.0.47"
asyncpg = "^0.31.0"
pydantic-settings = "^2.13.1"
alembic = "^1.18.4"
psycopg = "^3.3.3"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
